version: '3.8'

services:
    postgres-db:
        image: postgres:15.3
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
            interval: 10s
            timeout: 5s
            retries: 5

    wallet-api:
        build: .
        depends_on:
            postgres-db:
                condition: service_healthy
        environment:
            DATABASE_URL: ${POSTGRES_URL}
        ports:
            - '3000:3000'
        command: >
            sh -c "npx prisma migrate deploy &&
                   node dist/app.js"
